/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/tail1.glb 
*/

import { useGLTF } from '@react-three/drei'

export function Tail(props: any) {
  const { nodes, materials } = useGLTF('/tail1.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Cone.geometry} material={materials['Material.001']} material-color={props.material_color} rotation={[-Math.PI / 2, 0, 0]} scale={[0.6, 1, 0.6]} />
    </group>
  )
}

useGLTF.preload('/tail1.glb')